export const circuitTemplates = [
  {
    id: 'simple-switch-load',
    category: 'Core',
    name: 'Simple Switch Load',
    description: 'Single switch and single load with a shared A1 binding to start a correct one-wire pattern.',
    highlights: ['A1 binding seed', 'Switch to load handoff'],
    pageName: 'Template - Switch Load',
    schema: {
      version: '6.0.0',
      objects: [
        {
          type: 'i-text',
          left: 70,
          top: 40,
          text: 'Simple Switch Load',
          fontSize: 26,
          fontWeight: '700',
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 110,
          top: 180,
          width: 130,
          height: 70,
          rx: 10,
          ry: 10,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'A1',
          bindingRole: 'switch',
          symbolName: 'template switch'
        },
        {
          type: 'i-text',
          left: 138,
          top: 206,
          text: 'Switch A1',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 245,
          top: 212,
          x1: 0,
          y1: 0,
          x2: 260,
          y2: 0,
          stroke: '#7b6658',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 520,
          top: 170,
          width: 140,
          height: 90,
          rx: 45,
          ry: 45,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'A1',
          bindingRole: 'load',
          symbolName: 'template light'
        },
        {
          type: 'i-text',
          left: 560,
          top: 205,
          text: 'Load A1',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        }
      ]
    }
  },
  {
    id: 'motor-starter',
    category: 'Core',
    name: 'Motor Starter',
    description: 'Contactor, overload, and motor blocks laid out as a starter skeleton with B1 bindings.',
    highlights: ['Starter circuit skeleton', 'B1 control binding'],
    pageName: 'Template - Motor Starter',
    schema: {
      version: '6.0.0',
      objects: [
        {
          type: 'i-text',
          left: 70,
          top: 40,
          text: 'Motor Starter',
          fontSize: 26,
          fontWeight: '700',
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 100,
          top: 180,
          width: 150,
          height: 90,
          rx: 12,
          ry: 12,
          fill: '#f9f6ff',
          stroke: '#6d4d8a',
          strokeWidth: 2,
          bindingId: 'B1',
          bindingRole: 'switch',
          symbolName: 'start stop'
        },
        {
          type: 'i-text',
          left: 124,
          top: 214,
          text: 'Start/Stop B1',
          fontSize: 18,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 340,
          top: 180,
          width: 150,
          height: 90,
          rx: 12,
          ry: 12,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'B1',
          bindingRole: 'load',
          symbolName: 'contactor coil'
        },
        {
          type: 'i-text',
          left: 362,
          top: 214,
          text: 'Coil B1',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 585,
          top: 170,
          width: 170,
          height: 110,
          rx: 14,
          ry: 14,
          fill: '#f4fbf7',
          stroke: '#1f6a38',
          strokeWidth: 2,
          symbolName: 'motor block'
        },
        {
          type: 'i-text',
          left: 624,
          top: 212,
          text: 'Motor',
          fontSize: 22,
          fill: '#2f241d',
          selectable: false,
          evented: false
        }
      ]
    }
  },
  {
    id: 'three-phase-distribution',
    category: 'Core',
    name: '3-Phase Distribution',
    description: 'A starter distribution layout with three outgoing circuits and labeled phases for page setup.',
    highlights: ['Distribution board shell', 'Three outgoing circuits'],
    pageName: 'Template - 3 Phase Distribution',
    schema: {
      version: '6.0.0',
      objects: [
        {
          type: 'i-text',
          left: 70,
          top: 40,
          text: '3-Phase Distribution',
          fontSize: 26,
          fontWeight: '700',
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 90,
          top: 150,
          width: 180,
          height: 320,
          rx: 16,
          ry: 16,
          fill: '#f7f7f7',
          stroke: '#2f241d',
          strokeWidth: 2,
          symbolName: 'distribution board'
        },
        {
          type: 'i-text',
          left: 120,
          top: 172,
          text: 'Board',
          fontSize: 24,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 285,
          top: 215,
          x1: 0,
          y1: 0,
          x2: 350,
          y2: 0,
          stroke: '#c44d56',
          strokeWidth: 4,
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 285,
          top: 295,
          x1: 0,
          y1: 0,
          x2: 350,
          y2: 0,
          stroke: '#8c7a00',
          strokeWidth: 4,
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 285,
          top: 375,
          x1: 0,
          y1: 0,
          x2: 350,
          y2: 0,
          stroke: '#1f6a38',
          strokeWidth: 4,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 650,
          top: 190,
          width: 120,
          height: 50,
          rx: 8,
          ry: 8,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'C1',
          bindingRole: 'load',
          symbolName: 'outgoing circuit l1'
        },
        {
          type: 'rect',
          left: 650,
          top: 270,
          width: 120,
          height: 50,
          rx: 8,
          ry: 8,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'C2',
          bindingRole: 'load',
          symbolName: 'outgoing circuit l2'
        },
        {
          type: 'rect',
          left: 650,
          top: 350,
          width: 120,
          height: 50,
          rx: 8,
          ry: 8,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'C3',
          bindingRole: 'load',
          symbolName: 'outgoing circuit l3'
        }
      ]
    }
  },
  {
    id: 'solar-installation',
    category: 'Photovoltaic',
    name: 'Solar Installation',
    description:
      'Starter PV one-line with panel string, DC combiner, inverter, battery bank, disconnect, and AC handoff.',
    highlights: ['PV1 string link', 'B1 battery link', 'A1 AC export link'],
    pageName: 'Template - Solar Installation',
    schema: {
      version: '6.0.0',
      objects: [
        {
          type: 'i-text',
          left: 70,
          top: 40,
          text: 'Solar Installation',
          fontSize: 26,
          fontWeight: '700',
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'i-text',
          left: 70,
          top: 78,
          text: 'Starter layout: 12 panels / 5kW inverter / 10kWh battery',
          fontSize: 16,
          fill: '#6a5a50',
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 90,
          top: 170,
          width: 170,
          height: 90,
          rx: 16,
          ry: 16,
          fill: '#f9c74f22',
          stroke: '#8c7a00',
          strokeWidth: 2,
          bindingId: 'P1',
          bindingRole: 'load',
          symbolName: 'panel array'
        },
        {
          type: 'i-text',
          left: 122,
          top: 194,
          text: 'Panel Array',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'i-text',
          left: 140,
          top: 220,
          text: 'P1',
          fontSize: 18,
          fontWeight: '700',
          fill: '#8c7a00',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 262,
          top: 214,
          x1: 0,
          y1: 0,
          x2: 90,
          y2: 0,
          stroke: '#8c7a00',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 352,
          top: 184,
          width: 120,
          height: 62,
          rx: 12,
          ry: 12,
          fill: '#fff7f2',
          stroke: '#a85427',
          strokeWidth: 2,
          bindingId: 'P1',
          bindingRole: 'load',
          symbolName: 'dc combiner'
        },
        {
          type: 'i-text',
          left: 375,
          top: 206,
          text: 'DC Combiner',
          fontSize: 16,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 474,
          top: 214,
          x1: 0,
          y1: 0,
          x2: 100,
          y2: 0,
          stroke: '#a85427',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 576,
          top: 170,
          width: 150,
          height: 90,
          rx: 16,
          ry: 16,
          fill: '#f4fbf7',
          stroke: '#1f6a38',
          strokeWidth: 2,
          bindingId: 'A1',
          bindingRole: 'switch',
          symbolName: 'inverter'
        },
        {
          type: 'i-text',
          left: 620,
          top: 194,
          text: 'Inverter',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'i-text',
          left: 634,
          top: 220,
          text: 'A1 / P1',
          fontSize: 16,
          fontWeight: '700',
          fill: '#1f6a38',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 652,
          top: 262,
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 78,
          stroke: '#1f6a38',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 556,
          top: 342,
          width: 190,
          height: 86,
          rx: 16,
          ry: 16,
          fill: '#eef4ff',
          stroke: '#305f8f',
          strokeWidth: 2,
          bindingId: 'B1',
          bindingRole: 'load',
          symbolName: 'battery bank'
        },
        {
          type: 'i-text',
          left: 605,
          top: 368,
          text: 'Battery Bank',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'i-text',
          left: 636,
          top: 394,
          text: 'B1',
          fontSize: 16,
          fontWeight: '700',
          fill: '#305f8f',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 728,
          top: 214,
          x1: 0,
          y1: 0,
          x2: 96,
          y2: 0,
          stroke: '#1f6a38',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 826,
          top: 184,
          width: 126,
          height: 62,
          rx: 12,
          ry: 12,
          fill: '#fff7f2',
          stroke: '#c44d56',
          strokeWidth: 2,
          bindingId: 'A1',
          bindingRole: 'switch',
          symbolName: 'dc disconnect'
        },
        {
          type: 'i-text',
          left: 850,
          top: 206,
          text: 'Disconnect',
          fontSize: 16,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'line',
          left: 954,
          top: 214,
          x1: 0,
          y1: 0,
          x2: 96,
          y2: 0,
          stroke: '#c44d56',
          strokeWidth: 3,
          selectable: false,
          evented: false
        },
        {
          type: 'rect',
          left: 1052,
          top: 172,
          width: 170,
          height: 84,
          rx: 14,
          ry: 14,
          fill: '#f7f7f7',
          stroke: '#2f241d',
          strokeWidth: 2,
          bindingId: 'A1',
          bindingRole: 'load',
          symbolName: 'distribution board'
        },
        {
          type: 'i-text',
          left: 1088,
          top: 194,
          text: 'Main Board',
          fontSize: 20,
          fill: '#2f241d',
          selectable: false,
          evented: false
        },
        {
          type: 'i-text',
          left: 1116,
          top: 220,
          text: 'A1',
          fontSize: 16,
          fontWeight: '700',
          fill: '#2f241d',
          selectable: false,
          evented: false
        }
      ]
    }
  }
]
